# Generated by Django 5.0.7 on 2024-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('tgid', models.IntegerField()),
                ('myrole', models.CharField(choices=[('a', 'manager'), ('m', 'master'), ('c', 'client')])),
            ],
        ),
    ]
